//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using DA.DomainModel;

    public partial class DesignAcceleratorEntities : DbContext
    {
        public DesignAcceleratorEntities()
            : base(DBConnection.ConnectionString())
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Actions> tbl_Actions { get; set; }
        public virtual DbSet<tbl_Applications> tbl_Applications { get; set; }
        public virtual DbSet<tbl_AppVersion> tbl_AppVersion { get; set; }
        public virtual DbSet<tbl_Attribute> tbl_Attribute { get; set; }
        public virtual DbSet<tbl_AttributeType> tbl_AttributeType { get; set; }
        public virtual DbSet<tbl_AttributeValues> tbl_AttributeValues { get; set; }
        public virtual DbSet<tbl_BusinessRule> tbl_BusinessRule { get; set; }
        public virtual DbSet<tbl_BuzProd> tbl_BuzProd { get; set; }
        public virtual DbSet<tbl_BuzRulesAttrMapping> tbl_BuzRulesAttrMapping { get; set; }
        public virtual DbSet<tbl_ChannelAlert> tbl_ChannelAlert { get; set; }
        public virtual DbSet<tbl_ChannelAlertAttrMapping> tbl_ChannelAlertAttrMapping { get; set; }
        public virtual DbSet<tbl_Clients> tbl_Clients { get; set; }
        public virtual DbSet<tbl_DesignAccelerator> tbl_DesignAccelerator { get; set; }
        public virtual DbSet<tbl_Destination> tbl_Destination { get; set; }
        public virtual DbSet<tbl_DistributionType> tbl_DistributionType { get; set; }
        public virtual DbSet<tbl_ErrorLog> tbl_ErrorLog { get; set; }
        public virtual DbSet<tbl_FrequencyType> tbl_FrequencyType { get; set; }
        public virtual DbSet<tbl_Interface> tbl_Interface { get; set; }
        public virtual DbSet<tbl_InterfaceAttrMapping> tbl_InterfaceAttrMapping { get; set; }
        public virtual DbSet<tbl_LifeCycle> tbl_LifeCycle { get; set; }
        public virtual DbSet<tbl_LOB> tbl_LOB { get; set; }
        public virtual DbSet<tbl_ModeType> tbl_ModeType { get; set; }
        public virtual DbSet<tbl_Module> tbl_Module { get; set; }
        public virtual DbSet<tbl_PeriodType> tbl_PeriodType { get; set; }
        public virtual DbSet<tbl_Products> tbl_Products { get; set; }
        public virtual DbSet<tbl_Projects> tbl_Projects { get; set; }
        public virtual DbSet<tbl_Region> tbl_Region { get; set; }
        public virtual DbSet<tbl_Reports> tbl_Reports { get; set; }
        public virtual DbSet<tbl_Roles> tbl_Roles { get; set; }
        public virtual DbSet<tbl_RoleScreenMapping> tbl_RoleScreenMapping { get; set; }
        public virtual DbSet<tbl_Screens> tbl_Screens { get; set; }
        public virtual DbSet<tbl_Source> tbl_Source { get; set; }
        public virtual DbSet<tbl_Transactions> tbl_Transactions { get; set; }
        public virtual DbSet<tbl_TxnAttributeMapping> tbl_TxnAttributeMapping { get; set; }
        public virtual DbSet<tbl_UserActionArchives> tbl_UserActionArchives { get; set; }
        public virtual DbSet<tbl_UserData> tbl_UserData { get; set; }
        public virtual DbSet<tbl_DocsReferred> tbl_DocsReferred { get; set; }
    
        public virtual ObjectResult<sp_BusinessRuleMappingData_Result> sp_BusinessRuleMappingData(Nullable<int> dAid)
        {
            var dAidParameter = dAid.HasValue ?
                new ObjectParameter("DAid", dAid) :
                new ObjectParameter("DAid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BusinessRuleMappingData_Result>("sp_BusinessRuleMappingData", dAidParameter);
        }
    
        public virtual ObjectResult<sp_ExportExcelAttributes_Result> sp_ExportExcelAttributes(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExportExcelAttributes_Result>("sp_ExportExcelAttributes", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_ExportExcelBusinessRules_Result> sp_ExportExcelBusinessRules(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExportExcelBusinessRules_Result>("sp_ExportExcelBusinessRules", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_ExportExcelChannelsAlerts_Result> sp_ExportExcelChannelsAlerts(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExportExcelChannelsAlerts_Result>("sp_ExportExcelChannelsAlerts", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_ExportExcelInterface_Result> sp_ExportExcelInterface(Nullable<int> daid)
        {
            var daidParameter = daid.HasValue ?
                new ObjectParameter("Daid", daid) :
                new ObjectParameter("Daid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExportExcelInterface_Result>("sp_ExportExcelInterface", daidParameter);
        }
    
        public virtual ObjectResult<sp_ExportExcelProduct_Result> sp_ExportExcelProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExportExcelProduct_Result>("sp_ExportExcelProduct");
        }
    
        public virtual ObjectResult<sp_ExportExcelReports_Result> sp_ExportExcelReports(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExportExcelReports_Result>("sp_ExportExcelReports", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_ExportExcelTransaction_Result> sp_ExportExcelTransaction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExportExcelTransaction_Result>("sp_ExportExcelTransaction");
        }
    
        public virtual ObjectResult<sp_ExportExcelTransactionAttribute_Result> sp_ExportExcelTransactionAttribute(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExportExcelTransactionAttribute_Result>("sp_ExportExcelTransactionAttribute", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetAllBusinessRules_Result> sp_GetAllBusinessRules(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllBusinessRules_Result>("sp_GetAllBusinessRules", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetAllChannelsAndAlerts_Result> sp_GetAllChannelsAndAlerts(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllChannelsAndAlerts_Result>("sp_GetAllChannelsAndAlerts", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetAuthorizers_Result> sp_GetAuthorizers(string roleName, Nullable<int> userID)
        {
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAuthorizers_Result>("sp_GetAuthorizers", roleNameParameter, userIDParameter);
        }
    
        public virtual ObjectResult<sp_GetChannelsAndAlertsMappingData_Result> sp_GetChannelsAndAlertsMappingData(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetChannelsAndAlertsMappingData_Result>("sp_GetChannelsAndAlertsMappingData", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetInterfaceMapping_Result> sp_GetInterfaceMapping(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetInterfaceMapping_Result>("sp_GetInterfaceMapping", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetMappingViewModelData_Result> sp_GetMappingViewModelData(Nullable<int> dAID)
        {
            var dAIDParameter = dAID.HasValue ?
                new ObjectParameter("DAID", dAID) :
                new ObjectParameter("DAID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMappingViewModelData_Result>("sp_GetMappingViewModelData", dAIDParameter);
        }
    
        public virtual ObjectResult<sp_GetReports_Result> sp_GetReports(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReports_Result>("sp_GetReports", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetReportsMappingData_Result> sp_GetReportsMappingData(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReportsMappingData_Result>("sp_GetReportsMappingData", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetTransactionAttributesMapping_Result> sp_GetTransactionAttributesMapping(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTransactionAttributesMapping_Result>("sp_GetTransactionAttributesMapping", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetTransactionsForHeader_Result> sp_GetTransactionsForHeader(Nullable<int> dAId)
        {
            var dAIdParameter = dAId.HasValue ?
                new ObjectParameter("DAId", dAId) :
                new ObjectParameter("DAId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTransactionsForHeader_Result>("sp_GetTransactionsForHeader", dAIdParameter);
        }
    
        public virtual ObjectResult<sp_GetUserAccessInView_Result> sp_GetUserAccessInView(string screenName, Nullable<int> roleID)
        {
            var screenNameParameter = screenName != null ?
                new ObjectParameter("ScreenName", screenName) :
                new ObjectParameter("ScreenName", typeof(string));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUserAccessInView_Result>("sp_GetUserAccessInView", screenNameParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<sp_GetUsersToAuthorize_Result> sp_GetUsersToAuthorize(Nullable<int> authId)
        {
            var authIdParameter = authId.HasValue ?
                new ObjectParameter("AuthId", authId) :
                new ObjectParameter("AuthId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUsersToAuthorize_Result>("sp_GetUsersToAuthorize", authIdParameter);
        }
    
        public virtual ObjectResult<sp_InterfaceMappingData_Result> sp_InterfaceMappingData(Nullable<int> dAid)
        {
            var dAidParameter = dAid.HasValue ?
                new ObjectParameter("DAid", dAid) :
                new ObjectParameter("DAid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InterfaceMappingData_Result>("sp_InterfaceMappingData", dAidParameter);
        }
    }
}
