//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DocsReferred : IEntity
    {
        public int ClientID { get; set; }
        public int ProjectID { get; set; }
        public int ApplicationID { get; set; }
        public string DocVersion { get; set; }
    
        public virtual tbl_Applications tbl_Applications { get; set; }
        public virtual tbl_Clients tbl_Clients { get; set; }
        public virtual tbl_Projects tbl_Projects { get; set; }
        public EntityState EntityState { get; set; }
    }
}
