//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AttributeValues : IEntity
    {
        public int AttrValueID { get; set; }
        public int AttributeID { get; set; }
        public string AttributeValue { get; set; }
        public string isNegative { get; set; }
        public int daId { get; set; }
    
        public virtual tbl_Attribute tbl_Attribute { get; set; }
        public virtual tbl_DesignAccelerator tbl_DesignAccelerator { get; set; }
        public EntityState EntityState { get; set; }
    }
}
