//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DesignAccelerator : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DesignAccelerator()
        {
            this.tbl_Attribute = new HashSet<tbl_Attribute>();
            this.tbl_AttributeValues = new HashSet<tbl_AttributeValues>();
            this.tbl_BusinessRule = new HashSet<tbl_BusinessRule>();
            this.tbl_BuzProd = new HashSet<tbl_BuzProd>();
            this.tbl_ChannelAlert = new HashSet<tbl_ChannelAlert>();
            this.tbl_Destination = new HashSet<tbl_Destination>();
            this.tbl_DistributionType = new HashSet<tbl_DistributionType>();
            this.tbl_FrequencyType = new HashSet<tbl_FrequencyType>();
            this.tbl_Interface = new HashSet<tbl_Interface>();
            this.tbl_LifeCycle = new HashSet<tbl_LifeCycle>();
            this.tbl_LOB = new HashSet<tbl_LOB>();
            this.tbl_ModeType = new HashSet<tbl_ModeType>();
            this.tbl_Products = new HashSet<tbl_Products>();
            this.tbl_Reports = new HashSet<tbl_Reports>();
            this.tbl_Source = new HashSet<tbl_Source>();
            this.tbl_Transactions = new HashSet<tbl_Transactions>();
            this.tbl_TxnAttributeMapping = new HashSet<tbl_TxnAttributeMapping>();
        }
    
        public int daid { get; set; }
        public string daName { get; set; }
        public string dacomplete { get; set; }
        public Nullable<int> ModuleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Attribute> tbl_Attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AttributeValues> tbl_AttributeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessRule> tbl_BusinessRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BuzProd> tbl_BuzProd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChannelAlert> tbl_ChannelAlert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Destination> tbl_Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DistributionType> tbl_DistributionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FrequencyType> tbl_FrequencyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Interface> tbl_Interface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LifeCycle> tbl_LifeCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LOB> tbl_LOB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ModeType> tbl_ModeType { get; set; }
        public virtual tbl_Module tbl_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Products> tbl_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Reports> tbl_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Source> tbl_Source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Transactions> tbl_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TxnAttributeMapping> tbl_TxnAttributeMapping { get; set; }
        public EntityState EntityState { get; set; }
    }
}
