//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reports : IEntity
    {
        public int ReportID { get; set; }
        public string ReqReference { get; set; }
        public string ReportName { get; set; }
        public string ReportDesc { get; set; }
        public int TransactionSeq { get; set; }
        public int SourceID { get; set; }
        public int PeriodID { get; set; }
        public int daId { get; set; }
        public string IsLinked { get; set; }
    
        public virtual tbl_DesignAccelerator tbl_DesignAccelerator { get; set; }
        public virtual tbl_PeriodType tbl_PeriodType { get; set; }
        public virtual tbl_Source tbl_Source { get; set; }
        public virtual tbl_Transactions tbl_Transactions { get; set; }
        public EntityState EntityState { get; set; }
    }
}
