//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products : IEntity
    {
        public int ProductID { get; set; }
        public string ReqReference { get; set; }
        public int LobID { get; set; }
        public int BuzProdID { get; set; }
        public int daid { get; set; }
    
        public virtual tbl_BuzProd tbl_BuzProd { get; set; }
        public virtual tbl_DesignAccelerator tbl_DesignAccelerator { get; set; }
        public virtual tbl_LOB tbl_LOB { get; set; }
        public EntityState EntityState { get; set; }
    }
}
