//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BuzRulesAttrMapping : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BuzRulesAttrMapping()
        {
            this.tbl_BusinessRule = new HashSet<tbl_BusinessRule>();
        }
    
        public int BuzRulesAttrMapID { get; set; }
        public string ReqReference { get; set; }
        public string BuzRuleDesc { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AttrID1 { get; set; }
        public Nullable<int> AttrID2 { get; set; }
        public Nullable<int> AttrID3 { get; set; }
        public Nullable<int> AttrID4 { get; set; }
        public Nullable<int> AttrID5 { get; set; }
        public Nullable<int> AttrID6 { get; set; }
        public Nullable<int> AttrID7 { get; set; }
        public Nullable<int> AttrID8 { get; set; }
        public Nullable<int> AttrID9 { get; set; }
        public Nullable<int> AttrID10 { get; set; }
        public Nullable<int> AttrValueID1 { get; set; }
        public Nullable<int> AttrValueID2 { get; set; }
        public Nullable<int> AttrValueID3 { get; set; }
        public Nullable<int> AttrValueID4 { get; set; }
        public Nullable<int> AttrValueID5 { get; set; }
        public Nullable<int> AttrValueID6 { get; set; }
        public Nullable<int> AttrValueID7 { get; set; }
        public Nullable<int> AttrValueID8 { get; set; }
        public Nullable<int> AttrValueID9 { get; set; }
        public Nullable<int> AttrValueID10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessRule> tbl_BusinessRule { get; set; }
        public EntityState EntityState { get; set; }
    }
}
