//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transactions : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Transactions()
        {
            this.tbl_BusinessRule = new HashSet<tbl_BusinessRule>();
            this.tbl_ChannelAlert = new HashSet<tbl_ChannelAlert>();
            this.tbl_Interface = new HashSet<tbl_Interface>();
            this.tbl_Reports = new HashSet<tbl_Reports>();
            this.tbl_TxnAttributeMapping = new HashSet<tbl_TxnAttributeMapping>();
        }
    
        public int TransactionSeq { get; set; }
        public string ReqReference { get; set; }
        public string HighLevelTxnID { get; set; }
        public string HighLevelTxnDesc { get; set; }
        public int LifeCycleID { get; set; }
        public int daId { get; set; }
        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessRule> tbl_BusinessRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChannelAlert> tbl_ChannelAlert { get; set; }
        public virtual tbl_DesignAccelerator tbl_DesignAccelerator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Interface> tbl_Interface { get; set; }
        public virtual tbl_LifeCycle tbl_LifeCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Reports> tbl_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TxnAttributeMapping> tbl_TxnAttributeMapping { get; set; }
        public EntityState EntityState { get; set; }
    }
}
