//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InterfaceAttrMapping : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_InterfaceAttrMapping()
        {
            this.tbl_Interface = new HashSet<tbl_Interface>();
        }
    
        public int InterfaceAttrMapID { get; set; }
        public string ReqReference { get; set; }
        public string InterfaceDesc { get; set; }
        public int SourceId { get; set; }
        public int DestinationId { get; set; }
        public int ModeTypeId { get; set; }
        public Nullable<int> AttrID1 { get; set; }
        public Nullable<int> AttrValueID1 { get; set; }
        public Nullable<int> AttrID2 { get; set; }
        public Nullable<int> AttrValueID2 { get; set; }
        public Nullable<int> AttrID3 { get; set; }
        public Nullable<int> AttrValueID3 { get; set; }
        public Nullable<int> AttrID4 { get; set; }
        public Nullable<int> AttrValueID4 { get; set; }
        public Nullable<int> AttrID5 { get; set; }
        public Nullable<int> AttrValueID5 { get; set; }
        public Nullable<int> AttrID6 { get; set; }
        public Nullable<int> AttrValueID6 { get; set; }
        public Nullable<int> AttrID7 { get; set; }
        public Nullable<int> AttrValueID7 { get; set; }
        public Nullable<int> AttrID8 { get; set; }
        public Nullable<int> AttrValueID8 { get; set; }
        public Nullable<int> AttrID9 { get; set; }
        public Nullable<int> AttrValueID9 { get; set; }
        public Nullable<int> AttrID10 { get; set; }
        public Nullable<int> AttrValueID10 { get; set; }
    
        public virtual tbl_Destination tbl_Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Interface> tbl_Interface { get; set; }
        public virtual tbl_ModeType tbl_ModeType { get; set; }
        public virtual tbl_Source tbl_Source { get; set; }
        public EntityState EntityState { get; set; }
    }
}
