//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attribute : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Attribute()
        {
            this.tbl_AttributeValues = new HashSet<tbl_AttributeValues>();
            this.tbl_TxnAttributeMapping = new HashSet<tbl_TxnAttributeMapping>();
        }
    
        public int AttributeID { get; set; }
        public string AttributeDesc { get; set; }
        public int AttributeTypeID { get; set; }
        public int daId { get; set; }
    
        public virtual tbl_AttributeType tbl_AttributeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AttributeValues> tbl_AttributeValues { get; set; }
        public virtual tbl_DesignAccelerator tbl_DesignAccelerator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TxnAttributeMapping> tbl_TxnAttributeMapping { get; set; }
        public EntityState EntityState { get; set; }
    }
}
