//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserActionArchives : IEntity
    {
        public int UserArchiveID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
        public int CreatorID { get; set; }
        public int AuthID { get; set; }
        public int UserType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Active { get; set; }
        public System.DateTime ArchiveCreatedDate { get; set; }
        public int ActionID { get; set; }
        public EntityState EntityState { get; set; }
    }
}
