//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Projects : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Projects()
        {
            this.tbl_Applications = new HashSet<tbl_Applications>();
            this.tbl_DocsReferred = new HashSet<tbl_DocsReferred>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Applications> tbl_Applications { get; set; }
        public virtual tbl_Clients tbl_Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DocsReferred> tbl_DocsReferred { get; set; }
        public virtual tbl_Region tbl_Region { get; set; }
        public EntityState EntityState { get; set; }
    }
}
