//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Applications : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Applications()
        {
            this.tbl_DocsReferred = new HashSet<tbl_DocsReferred>();
            this.tbl_Module = new HashSet<tbl_Module>();
        }
    
        public int ApplicationID { get; set; }
        public string ApplicationName { get; set; }
        public int DocVersion { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> AppVersion { get; set; }
        public Nullable<int> BankType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DocsReferred> tbl_DocsReferred { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Module> tbl_Module { get; set; }
        public virtual tbl_Projects tbl_Projects { get; set; }
        public EntityState EntityState { get; set; }
    }
}
